// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const grantVesselAccess = `-- name: GrantVesselAccess :exec
INSERT INTO user_vessel_access (user_id, vessel_id, granted_by_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, vessel_id) DO NOTHING
`

type GrantVesselAccessParams struct {
	UserID      pgtype.UUID
	VesselID    pgtype.UUID
	GrantedByID pgtype.UUID
}

func (q *Queries) GrantVesselAccess(ctx context.Context, arg GrantVesselAccessParams) error {
	_, err := q.db.Exec(ctx, grantVesselAccess, arg.UserID, arg.VesselID, arg.GrantedByID)
	return err
}

const listAccessibleProjectsForUser = `-- name: ListAccessibleProjectsForUser :many
SELECT
  p.id, p.vessel_id, p.project_type, p.region, p.proposed_date, p.actual_date,
  p.stage, p.remarks, p.created_by_id, p.created_at, p.updated_at,
  v.name AS vessel_name, v.imo_number AS vessel_imo, v.organization_id,
  o.name AS organization_name
FROM user_vessel_access uva
JOIN projects p ON p.vessel_id = uva.vessel_id
JOIN vessels v  ON v.id = p.vessel_id
JOIN organizations o ON o.id = v.organization_id
WHERE uva.user_id = $1
ORDER BY v.name, p.proposed_date NULLS LAST, p.created_at
`

type ListAccessibleProjectsForUserRow struct {
	ID               pgtype.UUID
	VesselID         pgtype.UUID
	ProjectType      string
	Region           *string
	ProposedDate     pgtype.Date
	ActualDate       pgtype.Date
	Stage            string
	Remarks          *string
	CreatedByID      pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	VesselName       string
	VesselImo        *string
	OrganizationID   pgtype.UUID
	OrganizationName string
}

func (q *Queries) ListAccessibleProjectsForUser(ctx context.Context, userID pgtype.UUID) ([]ListAccessibleProjectsForUserRow, error) {
	rows, err := q.db.Query(ctx, listAccessibleProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccessibleProjectsForUserRow
	for rows.Next() {
		var i ListAccessibleProjectsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.VesselID,
			&i.ProjectType,
			&i.Region,
			&i.ProposedDate,
			&i.ActualDate,
			&i.Stage,
			&i.Remarks,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VesselName,
			&i.VesselImo,
			&i.OrganizationID,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessibleProjectsForUserInOrg = `-- name: ListAccessibleProjectsForUserInOrg :many
SELECT
  p.id, p.vessel_id, p.project_type, p.region, p.proposed_date, p.actual_date,
  p.stage, p.remarks, p.created_by_id, p.created_at, p.updated_at,
  v.name AS vessel_name, v.imo_number AS vessel_imo, v.organization_id,
  o.name AS organization_name
FROM user_vessel_access uva
JOIN projects p ON p.vessel_id = uva.vessel_id
JOIN vessels v  ON v.id = p.vessel_id
JOIN organizations o ON o.id = v.organization_id
WHERE uva.user_id = $1 AND v.organization_id = $2
ORDER BY v.name, p.proposed_date NULLS LAST, p.created_at
`

type ListAccessibleProjectsForUserInOrgParams struct {
	UserID         pgtype.UUID
	OrganizationID pgtype.UUID
}

type ListAccessibleProjectsForUserInOrgRow struct {
	ID               pgtype.UUID
	VesselID         pgtype.UUID
	ProjectType      string
	Region           *string
	ProposedDate     pgtype.Date
	ActualDate       pgtype.Date
	Stage            string
	Remarks          *string
	CreatedByID      pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	VesselName       string
	VesselImo        *string
	OrganizationID   pgtype.UUID
	OrganizationName string
}

func (q *Queries) ListAccessibleProjectsForUserInOrg(ctx context.Context, arg ListAccessibleProjectsForUserInOrgParams) ([]ListAccessibleProjectsForUserInOrgRow, error) {
	rows, err := q.db.Query(ctx, listAccessibleProjectsForUserInOrg, arg.UserID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccessibleProjectsForUserInOrgRow
	for rows.Next() {
		var i ListAccessibleProjectsForUserInOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.VesselID,
			&i.ProjectType,
			&i.Region,
			&i.ProposedDate,
			&i.ActualDate,
			&i.Stage,
			&i.Remarks,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VesselName,
			&i.VesselImo,
			&i.OrganizationID,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessibleVesselIDsForUser = `-- name: ListAccessibleVesselIDsForUser :many
SELECT vessel_id FROM user_vessel_access WHERE user_id = $1
`

func (q *Queries) ListAccessibleVesselIDsForUser(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAccessibleVesselIDsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var vessel_id pgtype.UUID
		if err := rows.Scan(&vessel_id); err != nil {
			return nil, err
		}
		items = append(items, vessel_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessibleVesselsForUser = `-- name: ListAccessibleVesselsForUser :many
SELECT v.id, v.name, v.imo_number, v.flag, v.vessel_type, v.organization_id, v.created_at,
       o.name AS organization_name
FROM user_vessel_access uva
JOIN vessels v        ON v.id = uva.vessel_id
JOIN organizations o  ON o.id = v.organization_id
WHERE uva.user_id = $1
ORDER BY o.name, v.name
`

type ListAccessibleVesselsForUserRow struct {
	ID               pgtype.UUID
	Name             string
	ImoNumber        *string
	Flag             *string
	VesselType       *string
	OrganizationID   pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	OrganizationName string
}

func (q *Queries) ListAccessibleVesselsForUser(ctx context.Context, userID pgtype.UUID) ([]ListAccessibleVesselsForUserRow, error) {
	rows, err := q.db.Query(ctx, listAccessibleVesselsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccessibleVesselsForUserRow
	for rows.Next() {
		var i ListAccessibleVesselsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImoNumber,
			&i.Flag,
			&i.VesselType,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllVesselAccessForUser = `-- name: RevokeAllVesselAccessForUser :exec
DELETE FROM user_vessel_access WHERE user_id = $1
`

func (q *Queries) RevokeAllVesselAccessForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllVesselAccessForUser, userID)
	return err
}

const revokeVesselAccess = `-- name: RevokeVesselAccess :exec
DELETE FROM user_vessel_access WHERE user_id = $1 AND vessel_id = $2
`

type RevokeVesselAccessParams struct {
	UserID   pgtype.UUID
	VesselID pgtype.UUID
}

func (q *Queries) RevokeVesselAccess(ctx context.Context, arg RevokeVesselAccessParams) error {
	_, err := q.db.Exec(ctx, revokeVesselAccess, arg.UserID, arg.VesselID)
	return err
}

const userHasVesselAccess = `-- name: UserHasVesselAccess :one
SELECT EXISTS (
  SELECT 1 FROM user_vessel_access WHERE user_id = $1 AND vessel_id = $2
) AS has_access
`

type UserHasVesselAccessParams struct {
	UserID   pgtype.UUID
	VesselID pgtype.UUID
}

func (q *Queries) UserHasVesselAccess(ctx context.Context, arg UserHasVesselAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasVesselAccess, arg.UserID, arg.VesselID)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}
