// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (user_id, action, entity_type, entity_id, project_id, metadata_json)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAuditLogParams struct {
	UserID       pgtype.UUID
	Action       string
	EntityType   string
	EntityID     pgtype.UUID
	ProjectID    pgtype.UUID
	MetadataJson []byte
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.ProjectID,
		arg.MetadataJson,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT a.id, a.user_id, a.action, a.entity_type, a.entity_id, a.project_id,
       a.metadata_json, a.created_at, u.name AS user_name, u.email AS user_email
FROM audit_logs a
JOIN users u ON u.id = a.user_id
ORDER BY a.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32
	Offset int32
}

type ListAuditLogsRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Action       string
	EntityType   string
	EntityID     pgtype.UUID
	ProjectID    pgtype.UUID
	MetadataJson []byte
	CreatedAt    pgtype.Timestamptz
	UserName     string
	UserEmail    string
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogsRow
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.ProjectID,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
