// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Action       string
	EntityType   string
	EntityID     pgtype.UUID
	ProjectID    pgtype.UUID
	MetadataJson []byte
	CreatedAt    pgtype.Timestamptz
}

type Organization struct {
	ID        pgtype.UUID
	Name      string
	Type      string
	CreatedAt pgtype.Timestamptz
}

type Project struct {
	ID           pgtype.UUID
	VesselID     pgtype.UUID
	ProjectType  string
	Region       *string
	ProposedDate pgtype.Date
	ActualDate   pgtype.Date
	Stage        string
	Remarks      *string
	CreatedByID  pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type ProjectFile struct {
	ID           pgtype.UUID
	ProjectID    pgtype.UUID
	FileName     string
	FileType     *string
	FileSize     *int64
	Category     string
	Status       string
	R2Key        *string
	R2UploadID   *string
	DeletedAt    pgtype.Timestamptz
	DeletedByID  pgtype.UUID
	UploadedByID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

type ProjectNote struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	Body      string
	AuthorID  pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Setting struct {
	Key       string
	Value     string
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID             pgtype.UUID
	Email          string
	Name           string
	PasswordHash   string
	Role           string
	OrganizationID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type UserVesselAccess struct {
	UserID      pgtype.UUID
	VesselID    pgtype.UUID
	GrantedAt   pgtype.Timestamptz
	GrantedByID pgtype.UUID
}

type Vessel struct {
	ID             pgtype.UUID
	Name           string
	ImoNumber      *string
	Flag           *string
	VesselType     *string
	OrganizationID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}
