// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one
INSERT INTO project_notes (project_id, body, author_id)
VALUES ($1, $2, $3)
RETURNING id, project_id, body, author_id, created_at
`

type CreateNoteParams struct {
	ProjectID pgtype.UUID
	Body      string
	AuthorID  pgtype.UUID
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (ProjectNote, error) {
	row := q.db.QueryRow(ctx, createNote, arg.ProjectID, arg.Body, arg.AuthorID)
	var i ProjectNote
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Body,
		&i.AuthorID,
		&i.CreatedAt,
	)
	return i, err
}

const listNotesForProject = `-- name: ListNotesForProject :many
SELECT n.id, n.project_id, n.body, n.author_id, n.created_at, u.name AS author_name
FROM project_notes n
JOIN users u ON u.id = n.author_id
WHERE n.project_id = $1
ORDER BY n.created_at DESC
`

type ListNotesForProjectRow struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	Body       string
	AuthorID   pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	AuthorName string
}

func (q *Queries) ListNotesForProject(ctx context.Context, projectID pgtype.UUID) ([]ListNotesForProjectRow, error) {
	rows, err := q.db.Query(ctx, listNotesForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotesForProjectRow
	for rows.Next() {
		var i ListNotesForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Body,
			&i.AuthorID,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
