// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, type) VALUES ($1, $2)
RETURNING id, name, type, created_at
`

type CreateOrganizationParams struct {
	Name string
	Type string
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Type)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const getClientOrganizationDetail = `-- name: GetClientOrganizationDetail :one
SELECT id, name, type, created_at
FROM organizations
WHERE id = $1 AND type = 'CLIENT'
`

func (q *Queries) GetClientOrganizationDetail(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getClientOrganizationDetail, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, type, created_at
FROM organizations
WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const listClientOrganizations = `-- name: ListClientOrganizations :many
SELECT
  o.id, o.name, o.type, o.created_at,
  (SELECT COUNT(*)::int FROM vessels v WHERE v.organization_id = o.id) AS vessel_count,
  (SELECT COUNT(*)::int FROM users u WHERE u.organization_id = o.id) AS user_count
FROM organizations o
WHERE o.type = 'CLIENT'
ORDER BY o.name
`

type ListClientOrganizationsRow struct {
	ID          pgtype.UUID
	Name        string
	Type        string
	CreatedAt   pgtype.Timestamptz
	VesselCount int32
	UserCount   int32
}

func (q *Queries) ListClientOrganizations(ctx context.Context) ([]ListClientOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listClientOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientOrganizationsRow
	for rows.Next() {
		var i ListClientOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
			&i.VesselCount,
			&i.UserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
