// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_files.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abortPendingFile = `-- name: AbortPendingFile :exec
DELETE FROM project_files WHERE id = $1 AND status = 'PENDING'
`

func (q *Queries) AbortPendingFile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, abortPendingFile, id)
	return err
}

const completeFile = `-- name: CompleteFile :one
UPDATE project_files
SET status       = 'COMPLETE',
    r2_upload_id = NULL  -- multipart upload finalised; id is no longer useful
WHERE id = $1
  AND status = 'PENDING'
RETURNING id, project_id, file_name, file_type, file_size, category, status,
          r2_key, uploaded_by_id, created_at
`

type CompleteFileRow struct {
	ID           pgtype.UUID
	ProjectID    pgtype.UUID
	FileName     string
	FileType     *string
	FileSize     *int64
	Category     string
	Status       string
	R2Key        *string
	UploadedByID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CompleteFile(ctx context.Context, id pgtype.UUID) (CompleteFileRow, error) {
	row := q.db.QueryRow(ctx, completeFile, id)
	var i CompleteFileRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.Category,
		&i.Status,
		&i.R2Key,
		&i.UploadedByID,
		&i.CreatedAt,
	)
	return i, err
}

const createPendingFile = `-- name: CreatePendingFile :one
INSERT INTO project_files (
    project_id, file_name, file_type, file_size, category, status,
    r2_key, r2_upload_id, uploaded_by_id
)
VALUES ($1, $2, $3, $4, $5, 'PENDING', $6, $7, $8)
RETURNING id, project_id, file_name, file_type, file_size, category, status,
          r2_key, r2_upload_id, uploaded_by_id, created_at
`

type CreatePendingFileParams struct {
	ProjectID    pgtype.UUID
	FileName     string
	FileType     *string
	FileSize     *int64
	Category     string
	R2Key        *string
	R2UploadID   *string
	UploadedByID pgtype.UUID
}

type CreatePendingFileRow struct {
	ID           pgtype.UUID
	ProjectID    pgtype.UUID
	FileName     string
	FileType     *string
	FileSize     *int64
	Category     string
	Status       string
	R2Key        *string
	R2UploadID   *string
	UploadedByID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreatePendingFile(ctx context.Context, arg CreatePendingFileParams) (CreatePendingFileRow, error) {
	row := q.db.QueryRow(ctx, createPendingFile,
		arg.ProjectID,
		arg.FileName,
		arg.FileType,
		arg.FileSize,
		arg.Category,
		arg.R2Key,
		arg.R2UploadID,
		arg.UploadedByID,
	)
	var i CreatePendingFileRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.Category,
		&i.Status,
		&i.R2Key,
		&i.R2UploadID,
		&i.UploadedByID,
		&i.CreatedAt,
	)
	return i, err
}

const getFile = `-- name: GetFile :one
SELECT id, project_id, file_name, file_type, file_size, category, status,
       r2_key, r2_upload_id, deleted_at, uploaded_by_id, created_at
FROM project_files
WHERE id = $1
`

type GetFileRow struct {
	ID           pgtype.UUID
	ProjectID    pgtype.UUID
	FileName     string
	FileType     *string
	FileSize     *int64
	Category     string
	Status       string
	R2Key        *string
	R2UploadID   *string
	DeletedAt    pgtype.Timestamptz
	UploadedByID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

// Returns the file regardless of status / deleted_at. Handlers do their own
// gating; this is the raw lookup.
func (q *Queries) GetFile(ctx context.Context, id pgtype.UUID) (GetFileRow, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i GetFileRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.Category,
		&i.Status,
		&i.R2Key,
		&i.R2UploadID,
		&i.DeletedAt,
		&i.UploadedByID,
		&i.CreatedAt,
	)
	return i, err
}

const listFilesForProject = `-- name: ListFilesForProject :many
SELECT pf.id, pf.project_id, pf.file_name, pf.file_type, pf.file_size, pf.category, pf.status,
       pf.r2_key, pf.uploaded_by_id, pf.created_at,
       u.name AS uploaded_by_name
FROM project_files pf
JOIN users u ON u.id = pf.uploaded_by_id
WHERE pf.project_id = $1
  AND pf.status = 'COMPLETE'
  AND pf.deleted_at IS NULL
ORDER BY pf.created_at DESC
`

type ListFilesForProjectRow struct {
	ID             pgtype.UUID
	ProjectID      pgtype.UUID
	FileName       string
	FileType       *string
	FileSize       *int64
	Category       string
	Status         string
	R2Key          *string
	UploadedByID   pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UploadedByName string
}

func (q *Queries) ListFilesForProject(ctx context.Context, projectID pgtype.UUID) ([]ListFilesForProjectRow, error) {
	rows, err := q.db.Query(ctx, listFilesForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilesForProjectRow
	for rows.Next() {
		var i ListFilesForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FileName,
			&i.FileType,
			&i.FileSize,
			&i.Category,
			&i.Status,
			&i.R2Key,
			&i.UploadedByID,
			&i.CreatedAt,
			&i.UploadedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesForProjects = `-- name: ListFilesForProjects :many
SELECT id, project_id, file_name, file_type, file_size, category, status,
       r2_key, uploaded_by_id, created_at
FROM project_files
WHERE project_id = ANY($1::uuid[])
  AND status = 'COMPLETE'
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListFilesForProjectsRow struct {
	ID           pgtype.UUID
	ProjectID    pgtype.UUID
	FileName     string
	FileType     *string
	FileSize     *int64
	Category     string
	Status       string
	R2Key        *string
	UploadedByID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

// Used by /clients/[id] to render Report/Feedback cells. Live, complete files only.
func (q *Queries) ListFilesForProjects(ctx context.Context, projectIds []pgtype.UUID) ([]ListFilesForProjectsRow, error) {
	rows, err := q.db.Query(ctx, listFilesForProjects, projectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilesForProjectsRow
	for rows.Next() {
		var i ListFilesForProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FileName,
			&i.FileType,
			&i.FileSize,
			&i.Category,
			&i.Status,
			&i.R2Key,
			&i.UploadedByID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFileR2Identifiers = `-- name: SetFileR2Identifiers :exec
UPDATE project_files
SET r2_key = $2, r2_upload_id = $3
WHERE id = $1 AND status = 'PENDING'
`

type SetFileR2IdentifiersParams struct {
	ID         pgtype.UUID
	R2Key      *string
	R2UploadID *string
}

func (q *Queries) SetFileR2Identifiers(ctx context.Context, arg SetFileR2IdentifiersParams) error {
	_, err := q.db.Exec(ctx, setFileR2Identifiers, arg.ID, arg.R2Key, arg.R2UploadID)
	return err
}

const softDeleteFile = `-- name: SoftDeleteFile :one
UPDATE project_files
SET deleted_at = now(), deleted_by_id = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, file_name, r2_key, deleted_at
`

type SoftDeleteFileParams struct {
	ID          pgtype.UUID
	DeletedByID pgtype.UUID
}

type SoftDeleteFileRow struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	FileName  string
	R2Key     *string
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) SoftDeleteFile(ctx context.Context, arg SoftDeleteFileParams) (SoftDeleteFileRow, error) {
	row := q.db.QueryRow(ctx, softDeleteFile, arg.ID, arg.DeletedByID)
	var i SoftDeleteFileRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FileName,
		&i.R2Key,
		&i.DeletedAt,
	)
	return i, err
}
