// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProjectsByStage = `-- name: CountProjectsByStage :many
SELECT stage, COUNT(*)::int AS count FROM projects GROUP BY stage
`

type CountProjectsByStageRow struct {
	Stage string
	Count int32
}

func (q *Queries) CountProjectsByStage(ctx context.Context) ([]CountProjectsByStageRow, error) {
	rows, err := q.db.Query(ctx, countProjectsByStage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountProjectsByStageRow
	for rows.Next() {
		var i CountProjectsByStageRow
		if err := rows.Scan(&i.Stage, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countProjectsByStageForOrg = `-- name: CountProjectsByStageForOrg :many
SELECT p.stage, COUNT(*)::int AS count
FROM projects p JOIN vessels v ON v.id = p.vessel_id
WHERE v.organization_id = $1
GROUP BY p.stage
`

type CountProjectsByStageForOrgRow struct {
	Stage string
	Count int32
}

func (q *Queries) CountProjectsByStageForOrg(ctx context.Context, organizationID pgtype.UUID) ([]CountProjectsByStageForOrgRow, error) {
	rows, err := q.db.Query(ctx, countProjectsByStageForOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountProjectsByStageForOrgRow
	for rows.Next() {
		var i CountProjectsByStageForOrgRow
		if err := rows.Scan(&i.Stage, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (vessel_id, project_type, region, proposed_date, stage, remarks, created_by_id)
VALUES ($1, $2, $3, $4, COALESCE($5, 'ENQUIRY'), $6, $7)
RETURNING id, vessel_id, project_type, region, proposed_date, actual_date, stage, remarks, created_by_id, created_at, updated_at
`

type CreateProjectParams struct {
	VesselID     pgtype.UUID
	ProjectType  string
	Region       *string
	ProposedDate pgtype.Date
	Column5      interface{}
	Remarks      *string
	CreatedByID  pgtype.UUID
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.VesselID,
		arg.ProjectType,
		arg.Region,
		arg.ProposedDate,
		arg.Column5,
		arg.Remarks,
		arg.CreatedByID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.VesselID,
		&i.ProjectType,
		&i.Region,
		&i.ProposedDate,
		&i.ActualDate,
		&i.Stage,
		&i.Remarks,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT
  p.id, p.vessel_id, p.project_type, p.region, p.proposed_date, p.actual_date,
  p.stage, p.remarks, p.created_by_id, p.created_at, p.updated_at,
  v.name AS vessel_name, v.imo_number AS vessel_imo, v.organization_id,
  o.name AS organization_name
FROM projects p
JOIN vessels v ON v.id = p.vessel_id
JOIN organizations o ON o.id = v.organization_id
WHERE p.id = $1
`

type GetProjectRow struct {
	ID               pgtype.UUID
	VesselID         pgtype.UUID
	ProjectType      string
	Region           *string
	ProposedDate     pgtype.Date
	ActualDate       pgtype.Date
	Stage            string
	Remarks          *string
	CreatedByID      pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	VesselName       string
	VesselImo        *string
	OrganizationID   pgtype.UUID
	OrganizationName string
}

func (q *Queries) GetProject(ctx context.Context, id pgtype.UUID) (GetProjectRow, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i GetProjectRow
	err := row.Scan(
		&i.ID,
		&i.VesselID,
		&i.ProjectType,
		&i.Region,
		&i.ProposedDate,
		&i.ActualDate,
		&i.Stage,
		&i.Remarks,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VesselName,
		&i.VesselImo,
		&i.OrganizationID,
		&i.OrganizationName,
	)
	return i, err
}

const listAllProjects = `-- name: ListAllProjects :many
SELECT
  p.id, p.vessel_id, p.project_type, p.region, p.proposed_date, p.actual_date,
  p.stage, p.remarks, p.created_by_id, p.created_at, p.updated_at,
  v.name AS vessel_name, v.imo_number AS vessel_imo, v.organization_id,
  o.name AS organization_name
FROM projects p
JOIN vessels v ON v.id = p.vessel_id
JOIN organizations o ON o.id = v.organization_id
ORDER BY p.updated_at DESC
`

type ListAllProjectsRow struct {
	ID               pgtype.UUID
	VesselID         pgtype.UUID
	ProjectType      string
	Region           *string
	ProposedDate     pgtype.Date
	ActualDate       pgtype.Date
	Stage            string
	Remarks          *string
	CreatedByID      pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	VesselName       string
	VesselImo        *string
	OrganizationID   pgtype.UUID
	OrganizationName string
}

func (q *Queries) ListAllProjects(ctx context.Context) ([]ListAllProjectsRow, error) {
	rows, err := q.db.Query(ctx, listAllProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllProjectsRow
	for rows.Next() {
		var i ListAllProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.VesselID,
			&i.ProjectType,
			&i.Region,
			&i.ProposedDate,
			&i.ActualDate,
			&i.Stage,
			&i.Remarks,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VesselName,
			&i.VesselImo,
			&i.OrganizationID,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByOrg = `-- name: ListProjectsByOrg :many
SELECT
  p.id, p.vessel_id, p.project_type, p.region, p.proposed_date, p.actual_date,
  p.stage, p.remarks, p.created_by_id, p.created_at, p.updated_at,
  v.name AS vessel_name, v.imo_number AS vessel_imo, v.organization_id,
  o.name AS organization_name
FROM projects p
JOIN vessels v ON v.id = p.vessel_id
JOIN organizations o ON o.id = v.organization_id
WHERE v.organization_id = $1
ORDER BY v.name, p.proposed_date NULLS LAST, p.created_at
`

type ListProjectsByOrgRow struct {
	ID               pgtype.UUID
	VesselID         pgtype.UUID
	ProjectType      string
	Region           *string
	ProposedDate     pgtype.Date
	ActualDate       pgtype.Date
	Stage            string
	Remarks          *string
	CreatedByID      pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	VesselName       string
	VesselImo        *string
	OrganizationID   pgtype.UUID
	OrganizationName string
}

func (q *Queries) ListProjectsByOrg(ctx context.Context, organizationID pgtype.UUID) ([]ListProjectsByOrgRow, error) {
	rows, err := q.db.Query(ctx, listProjectsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsByOrgRow
	for rows.Next() {
		var i ListProjectsByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.VesselID,
			&i.ProjectType,
			&i.Region,
			&i.ProposedDate,
			&i.ActualDate,
			&i.Stage,
			&i.Remarks,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VesselName,
			&i.VesselImo,
			&i.OrganizationID,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByVessel = `-- name: ListProjectsByVessel :many
SELECT
  p.id, p.vessel_id, p.project_type, p.region, p.proposed_date, p.actual_date,
  p.stage, p.remarks, p.created_by_id, p.created_at, p.updated_at,
  v.name AS vessel_name, v.imo_number AS vessel_imo, v.organization_id,
  o.name AS organization_name
FROM projects p
JOIN vessels v ON v.id = p.vessel_id
JOIN organizations o ON o.id = v.organization_id
WHERE p.vessel_id = $1
ORDER BY p.created_at DESC
`

type ListProjectsByVesselRow struct {
	ID               pgtype.UUID
	VesselID         pgtype.UUID
	ProjectType      string
	Region           *string
	ProposedDate     pgtype.Date
	ActualDate       pgtype.Date
	Stage            string
	Remarks          *string
	CreatedByID      pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	VesselName       string
	VesselImo        *string
	OrganizationID   pgtype.UUID
	OrganizationName string
}

func (q *Queries) ListProjectsByVessel(ctx context.Context, vesselID pgtype.UUID) ([]ListProjectsByVesselRow, error) {
	rows, err := q.db.Query(ctx, listProjectsByVessel, vesselID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsByVesselRow
	for rows.Next() {
		var i ListProjectsByVesselRow
		if err := rows.Scan(
			&i.ID,
			&i.VesselID,
			&i.ProjectType,
			&i.Region,
			&i.ProposedDate,
			&i.ActualDate,
			&i.Stage,
			&i.Remarks,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VesselName,
			&i.VesselImo,
			&i.OrganizationID,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectMeta = `-- name: UpdateProjectMeta :one
UPDATE projects
SET region        = COALESCE($2, region),
    proposed_date = COALESCE($3, proposed_date),
    actual_date   = COALESCE($4, actual_date),
    updated_at    = now()
WHERE id = $1
RETURNING id, vessel_id, project_type, region, proposed_date, actual_date, stage, remarks, created_by_id, created_at, updated_at
`

type UpdateProjectMetaParams struct {
	ID           pgtype.UUID
	Region       *string
	ProposedDate pgtype.Date
	ActualDate   pgtype.Date
}

func (q *Queries) UpdateProjectMeta(ctx context.Context, arg UpdateProjectMetaParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectMeta,
		arg.ID,
		arg.Region,
		arg.ProposedDate,
		arg.ActualDate,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.VesselID,
		&i.ProjectType,
		&i.Region,
		&i.ProposedDate,
		&i.ActualDate,
		&i.Stage,
		&i.Remarks,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectRemarks = `-- name: UpdateProjectRemarks :one
UPDATE projects SET remarks = $2, updated_at = now()
WHERE id = $1
RETURNING id, vessel_id, project_type, region, proposed_date, actual_date, stage, remarks, created_by_id, created_at, updated_at
`

type UpdateProjectRemarksParams struct {
	ID      pgtype.UUID
	Remarks *string
}

func (q *Queries) UpdateProjectRemarks(ctx context.Context, arg UpdateProjectRemarksParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectRemarks, arg.ID, arg.Remarks)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.VesselID,
		&i.ProjectType,
		&i.Region,
		&i.ProposedDate,
		&i.ActualDate,
		&i.Stage,
		&i.Remarks,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectStage = `-- name: UpdateProjectStage :one
UPDATE projects SET stage = $2, updated_at = now()
WHERE id = $1
RETURNING id, vessel_id, project_type, region, proposed_date, actual_date, stage, remarks, created_by_id, created_at, updated_at
`

type UpdateProjectStageParams struct {
	ID    pgtype.UUID
	Stage string
}

func (q *Queries) UpdateProjectStage(ctx context.Context, arg UpdateProjectStageParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectStage, arg.ID, arg.Stage)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.VesselID,
		&i.ProjectType,
		&i.Region,
		&i.ProposedDate,
		&i.ActualDate,
		&i.Stage,
		&i.Remarks,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
