// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recipients.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listNivyashUsers = `-- name: ListNivyashUsers :many
SELECT u.id, u.email, u.name, u.role
FROM users u
JOIN organizations o ON o.id = u.organization_id
WHERE o.type = 'NIVYASH'
ORDER BY u.email
`

type ListNivyashUsersRow struct {
	ID    pgtype.UUID
	Email string
	Name  string
	Role  string
}

// Nivyash internal users — admin and staff. Used to alert the office when a
// client uploads feedback.
func (q *Queries) ListNivyashUsers(ctx context.Context) ([]ListNivyashUsersRow, error) {
	rows, err := q.db.Query(ctx, listNivyashUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNivyashUsersRow
	for rows.Next() {
		var i ListNivyashUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithVesselAccess = `-- name: ListUsersWithVesselAccess :many

SELECT u.id, u.email, u.name, u.role
FROM users u
JOIN user_vessel_access uva ON uva.user_id = u.id
WHERE uva.vessel_id = $1
ORDER BY u.email
`

type ListUsersWithVesselAccessRow struct {
	ID    pgtype.UUID
	Email string
	Name  string
	Role  string
}

// Recipients for email notifications. Kept in their own file so the email
// triggers can find what they need without going through generic user/vessel
// queries.
// All users (admin or viewer) who currently have a grant on this vessel.
func (q *Queries) ListUsersWithVesselAccess(ctx context.Context, vesselID pgtype.UUID) ([]ListUsersWithVesselAccessRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithVesselAccess, vesselID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersWithVesselAccessRow
	for rows.Next() {
		var i ListUsersWithVesselAccessRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
