// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, password_hash, role, organization_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, name, role, organization_id, created_at
`

type CreateUserParams struct {
	Email          string
	Name           string
	PasswordHash   string
	Role           string
	OrganizationID pgtype.UUID
}

type CreateUserRow struct {
	ID             pgtype.UUID
	Email          string
	Name           string
	Role           string
	OrganizationID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.Role,
		arg.OrganizationID,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.OrganizationID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, role, organization_id, created_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.OrganizationID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, role, organization_id, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.OrganizationID,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.email, u.name, u.role, u.organization_id, u.created_at, o.name AS organization_name, o.type AS organization_type
FROM users u
JOIN organizations o ON o.id = u.organization_id
ORDER BY o.name, u.name
`

type ListUsersRow struct {
	ID               pgtype.UUID
	Email            string
	Name             string
	Role             string
	OrganizationID   pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	OrganizationName string
	OrganizationType string
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.OrganizationName,
			&i.OrganizationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByOrg = `-- name: ListUsersByOrg :many
SELECT id, email, name, role, organization_id, created_at
FROM users
WHERE organization_id = $1
ORDER BY name
`

type ListUsersByOrgRow struct {
	ID             pgtype.UUID
	Email          string
	Name           string
	Role           string
	OrganizationID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) ListUsersByOrg(ctx context.Context, organizationID pgtype.UUID) ([]ListUsersByOrgRow, error) {
	rows, err := q.db.Query(ctx, listUsersByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByOrgRow
	for rows.Next() {
		var i ListUsersByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.OrganizationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
