// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vessels.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVessel = `-- name: CreateVessel :one
INSERT INTO vessels (name, imo_number, flag, vessel_type, organization_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, imo_number, flag, vessel_type, organization_id, created_at
`

type CreateVesselParams struct {
	Name           string
	ImoNumber      *string
	Flag           *string
	VesselType     *string
	OrganizationID pgtype.UUID
}

func (q *Queries) CreateVessel(ctx context.Context, arg CreateVesselParams) (Vessel, error) {
	row := q.db.QueryRow(ctx, createVessel,
		arg.Name,
		arg.ImoNumber,
		arg.Flag,
		arg.VesselType,
		arg.OrganizationID,
	)
	var i Vessel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImoNumber,
		&i.Flag,
		&i.VesselType,
		&i.OrganizationID,
		&i.CreatedAt,
	)
	return i, err
}

const getVessel = `-- name: GetVessel :one
SELECT v.id, v.name, v.imo_number, v.flag, v.vessel_type, v.organization_id, v.created_at,
       o.name AS organization_name
FROM vessels v
JOIN organizations o ON o.id = v.organization_id
WHERE v.id = $1
`

type GetVesselRow struct {
	ID               pgtype.UUID
	Name             string
	ImoNumber        *string
	Flag             *string
	VesselType       *string
	OrganizationID   pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	OrganizationName string
}

func (q *Queries) GetVessel(ctx context.Context, id pgtype.UUID) (GetVesselRow, error) {
	row := q.db.QueryRow(ctx, getVessel, id)
	var i GetVesselRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImoNumber,
		&i.Flag,
		&i.VesselType,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.OrganizationName,
	)
	return i, err
}

const listVessels = `-- name: ListVessels :many
SELECT v.id, v.name, v.imo_number, v.flag, v.vessel_type, v.organization_id, v.created_at,
       o.name AS organization_name
FROM vessels v
JOIN organizations o ON o.id = v.organization_id
ORDER BY v.name
`

type ListVesselsRow struct {
	ID               pgtype.UUID
	Name             string
	ImoNumber        *string
	Flag             *string
	VesselType       *string
	OrganizationID   pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	OrganizationName string
}

func (q *Queries) ListVessels(ctx context.Context) ([]ListVesselsRow, error) {
	rows, err := q.db.Query(ctx, listVessels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVesselsRow
	for rows.Next() {
		var i ListVesselsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImoNumber,
			&i.Flag,
			&i.VesselType,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVesselsByOrg = `-- name: ListVesselsByOrg :many
SELECT v.id, v.name, v.imo_number, v.flag, v.vessel_type, v.organization_id, v.created_at,
       o.name AS organization_name
FROM vessels v
JOIN organizations o ON o.id = v.organization_id
WHERE v.organization_id = $1
ORDER BY v.name
`

type ListVesselsByOrgRow struct {
	ID               pgtype.UUID
	Name             string
	ImoNumber        *string
	Flag             *string
	VesselType       *string
	OrganizationID   pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	OrganizationName string
}

func (q *Queries) ListVesselsByOrg(ctx context.Context, organizationID pgtype.UUID) ([]ListVesselsByOrgRow, error) {
	rows, err := q.db.Query(ctx, listVesselsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVesselsByOrgRow
	for rows.Next() {
		var i ListVesselsByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImoNumber,
			&i.Flag,
			&i.VesselType,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
